---
title: "Dataset report of a burrow data file"
author: "Suzanne Fox"
date: "February 2017"
output: word_document
df_print: kable
---

```{r setup, echo=FALSE,  message=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(GGally)

```

## Run the Burrow function to analyse the source data

```{r Burrow, echo=FALSE,  message=FALSE, warning=FALSE}

workdir <- "C:/Users/Suzanne/OneDrive - Suzanne Fox/Dissertation/R/"
setwd(workdir)

# make a dataframe of the test data
#Data.source <- iris
#Data.title <- "Iris dataset"

Data.source <- read.csv("TestData.csv", stringsAsFactors = FALSE)
Data.title <- "synthetic test dataset"

# make a dataframe of the output from the burrow function for this data
source("C:/Users/Suzanne/OneDrive - Suzanne Fox/Dissertation/R/Burrow.R")
Burrow.test <- Burrow(Data.source, Data.title, TRUE)
Data.burrow <- Burrow.test$data

# Get all the variables which are number fields
Data.vars.number <- subset(Data.burrow, 
                           InfoType=="BEST GUESS" 
                           & (myData1=="NUMBER" | myData1=="DECIMALS"))


```

## Dataset details

```{r structure, echo=FALSE, comment="", collapse=TRUE}
# Dataset name
Data.name <- subset(Data.burrow, InfoLevel=="DATASET" &  InfoType=="SOURCEDATA",
c("InfoDetail"))
cat(paste("Source data name -", Data.name))

# Description
Data.description <- subset(Data.burrow, InfoLevel=="DATASET" & InfoType=="SOURCE",
c("InfoDetail"))
cat(paste("Source data description -", Data.description))

# Run time
Data.rundate <- subset(Data.burrow, InfoLevel=="HEADER" & InfoType=="RUN DATE",
c("InfoDetail"))
cat(paste("Burrow data created -", Data.rundate))

# Dataset structure ================================================

numcols <- subset(Data.burrow, Variable1=="NUMCOLS", c("myData1"))
numrows <- subset(Data.burrow, Variable1=="NUMROWS", c("myData1"))
outtext <- sprintf("Dataset dimensions - %s columns (variables) and %s rows (cases)",numcols, numrows)

cat(outtext)
```

## Best Guess at datatype for each variable


```{r datatypes, echo=FALSE, comment="", collapse=TRUE}
Data.bestguess <- subset(Data.burrow, InfoType=="BEST GUESS", select=c("Variable1","myData1"))
names(Data.bestguess) <- c("Variable","Datatype")

print(Data.bestguess, row.names=FALSE)

```

## Variable analysis - level of missing values


```{r missing, echo=FALSE, comment="", fig.width=9, fig.height=6, collapse=TRUE}
Data.missing <- subset(Data.burrow, InfoDetail=="DENSITY_NA", select=c("Variable1","myData1"))
Data.missing$myData1 <- as.numeric(Data.missing$myData1) * 100
names(Data.missing) <- c("Variable","Missing")

# See if there are any missing, and find max level
Missing.total <- sum(Data.missing$Missing)
Missing.max <- max(Data.missing$Missing)

if (Missing.total==0) {
  cat("There were no missing values for any variable")
} else {
  ggplot(data=Data.missing, 
       aes(x=Variable,  y=Missing)) +
       geom_bar(colour="black", fill="#4C1E9C",
       width=.8, stat="identity") +
       xlab("Variables") + ylab("% of Total Sample") +
       ggtitle("Overview of Missing Values") +
       theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
}

```

## Variable analysis - level of unique values


```{r uniques, echo=FALSE, comment="", collapse=TRUE, fig.width=9, fig.height=6}
Data.unique <- subset(Data.burrow, InfoDetail=="DENSITY_UNIQUES", select=c("Variable1","myData1"))
Data.unique$myData1 <- as.numeric(Data.unique$myData1) * 100
names(Data.unique) <- c("Variable","Unique")

ggplot(data=Data.unique, 
       aes(x=Variable,  y=Unique)) +
       geom_bar(colour="black", fill="#4C1E9C",
       width=.8, stat="identity") +
       xlab("Variables") + ylab("% of Total Sample") +
       ggtitle("Overview of Unique Values") +
       theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

```

## Variable analysis - correlations

```{r correlations, echo=FALSE, message=FALSE, warning=FALSE, comment="", collapse=TRUE}

if (nrow(Data.vars.number)==0) {
  print("No numeric variables in this dataset")

} else {
  Data.pairs <- as.list(Data.vars.number[c("Variable1")])
  Data.scatter <- Data.source[,c(Data.pairs$Variable1)]

  ptot <- ncol(Data.scatter)

  p1 <- 1
  p2 <- 4
  if (ptot < 4 ) {p2==ptot}

  while(ptot > 0) {
    Data.plot <- Data.scatter[,c(p1:p2)]
    print(ggpairs(Data.plot))

    ptot <- ptot-4
    if (ptot > 0 ) {
      p1 <- p1+4
      p2 <- p2+4
      if (ptot < 4 ) {p2==ptot}
    }
  }
}
```

## Variable analysis - distributions and outliers for numeric variables

```{r outliers, echo=FALSE, comment="", collapse=TRUE, fig.width=9, fig.height=6}

if (nrow(Data.vars.number)==0) {
   print("No numeric variables in this dataset")
  
 } else {
  for (i in 1:nrow(Data.vars.number)) {
    # Generate data
    data.title <- Data.vars.number[i,c("Variable1")]
    outtext <- paste("Charting -",data.title," datatype is ",Data.vars.number[i,c("myData1")])
    print(outtext)
    
    data.orig <- as.data.frame(Data.source[,c(data.title)])
    xx <- plot_nums(data.orig, data.title)
    plot(xx)
  }
}

```